services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=collaboration_tool
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MD_DB=${MD_DB}
      - MD_TOKEN=${MD_TOKEN}
      - OS_KEY=${OS_KEY}
      - NUAR_BASE_URL=${NUAR_BASE_URL}
      - NUAR_KEY=${NUAR_KEY}
      - NUAR_ZOOM_LEVEL=${NUAR_ZOOM_LEVEL}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    environment:
      POSTGRES_DB: collaboration_tool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
